In [156]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
data=iris.data
target=iris.target
features=iris.feature_names
tnames=iris.target_names

In [160]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [199]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [198]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [57]:
#Exercici1
#Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

data= iris['data'][:10]
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [77]:
target=iris['target'][:10]
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [161]:
#Exercici2
#Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.

print(target.ndim)
print(data.ndim)

print(data.shape)
print(target.shape)

data= iris['data']
newtarget=iris['target'].reshape(-1,1)

concat=np.concatenate((data,newtarget), axis=1)
print(concat[:5])

1
2
(150, 4)
(150,)
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [214]:
#Exercici 3
#Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") 
#i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.


longitud_sepal = iris.data[:, 0] 
longitud_petal = iris.data[:, 2] 

desv_est1 = round(np.std(longitud_sepal),2) 
desv_est2 = round(np.std(longitud_petal),2) 
print(desv_est1)
print(desv_est2)

mitjana1 = round(np.mean(longitud_sepal),2)
mitjana2 = round(np.mean(longitud_petal),2) 
print(mitjana1)
print(mitjana2)

#lista=np.array(iris["sepal length (cm)"])
#media=lista.mean()
#desv_est= np.std()
#print(mean)

0.83
1.76
5.84
3.76


In [162]:
#Exercici 4
#Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

from numpy import random

arr = np.array(concat)[:20]
print(random.permutation(arr))

[[5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [4.8 3.  1.4 0.1 0. ]]


In [197]:
#Exercici 5
#Crea una matriu que mostri: 
#La mitjana de cada característica per espècie. 
#La desviació estàndard de cada característica per espècie.

iris = load_iris()
data = iris.data  
target = iris.target 
especies = np.unique(target)
total_media=[]

for tipus in especies:
    data_specie = data[target == specie]
    
    media = np.mean(data_specie, axis=0)
    desv_std = np.std(data_specie, axis=0)
    
    nombre_especie = iris.target_names[tipus]

    print(f'Especie {nombre_especie}:')
    print(f'Media: {media}')
    print(f'Desviación Estándar: {desv_std}')
    
    

Especie setosa:
Media: [6.588 2.974 5.552 2.026]
Desviación Estándar: [0.62948868 0.31925538 0.54634787 0.27188968]
Especie versicolor:
Media: [6.588 2.974 5.552 2.026]
Desviación Estándar: [0.62948868 0.31925538 0.54634787 0.27188968]
Especie virginica:
Media: [6.588 2.974 5.552 2.026]
Desviación Estándar: [0.62948868 0.31925538 0.54634787 0.27188968]


In [212]:
#Exercici 6
#Calcula la quantitat de mostres per espècie.

cantidad_muestras=np.bincount(target)

for tipus, cantidad in enumerate(cantidad_muestras):
    nombre_especie = iris.target_names[tipus]
    print(f'Especie {nombre_especie}: {cantidad} muestras')

Especie setosa: 50 muestras
Especie versicolor: 50 muestras
Especie virginica: 50 muestras


In [ ]:
#Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

In [292]:
especies = np.unique(target)
media_longitud=[]
max_media = 0
medias_longitud_total_sepal=[]

for tipus in especies:
    data_especie = data[target == tipus]
    nombre_especie = iris.target_names[tipus]
    longitud_sepal = data_especie[:, 0]
    media_longitud = round(np.mean(longitud_sepal),2)

    print(f'Especie {nombre_especie}:')
    print(f"Media de longitud del sépalo: {media_longitud}")
    
    medias_longitud_total_sepal.append(media_longitud)
   
    if media_longitud>max_media:
        max_media=media_longitud
        print(f'\nLa especie con el valor máximo es: {nombre_especie} con un valor de: {max_media}')

print(medias_longitud_total_sepal)

Especie setosa:
Media de longitud del sépalo: 5.01

La especie con el valor máximo es: setosa con un valor de: 5.01
Especie versicolor:
Media de longitud del sépalo: 5.94

La especie con el valor máximo es: versicolor con un valor de: 5.94
Especie virginica:
Media de longitud del sépalo: 6.59

La especie con el valor máximo es: virginica con un valor de: 6.59
[5.01, 5.94, 6.59]


In [242]:
#Exercici 7
#Calcula la matriu de correlació entre les variables.

correlacion=np.corrcoef(data, rowvar=False)
print(correlacion)

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]


In [258]:
#Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 

longitud_petal=iris.data[:, 2]
med_longitud_petal = np.mean(longitud_petal)
print(f"Media de longitud del petal: {med_longitud}")

valores_mayores=longitud_petal[longitud_petal>med_longitud_petal]
print(f"\nEls valors majors a la mitjana són: {valores_mayores}")


#Troba la mostra amb els pètals més grans.
indice_petal=np.argmax(longitud_petal)
mas_grande=data[indice_petal,:]
print (f"\nLa mostra amb els pètals més grans es: {mas_grande }")


Media de longitud del petal: 3.76

Els valors majors a la mitjana són: [4.7 4.5 4.9 4.  4.6 4.5 4.7 4.6 3.9 4.2 4.  4.7 4.4 4.5 4.1 4.5 3.9 4.8
 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.8 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.  4.4
 4.6 4.  4.2 4.2 4.2 4.3 4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1 5.1
 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.  4.8 4.9 5.6
 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9 5.7 5.2 5.
 5.2 5.4 5.1]

La mostra amb els pètals més grans es: [7.7 2.6 6.9 2.3]


In [312]:
#Ejercicio 8
#Halla la especie con la mayor diferencia entre la longitud media de sépalos y pétalos.

print(f'Longitud media setal: {medias_longitud_total_sepal}')

medias_longitud_total_petal=[]

for tipus in especies:
    data_especie = data[target == tipus]
    nombre_especie = iris.target_names[tipus]
    longitud_petal = data_especie[:, 2]
    media_longitud = round(np.mean(longitud_petal),2)
    
    medias_longitud_total_petal.append(media_longitud)

print(f'Longitud media petal: {medias_longitud_total_petal}')

diferencia=abs(medias_longitud_total_sepal-medias_longitud_total_petal)
print(f'Diferencia de longitudes segun especies: {diferencia}')
maximo=np.argmax(diferencia)
iris.target_names[(maximo)]
print(f'\nLa especie con la mayor diferencia entre la longitud media de sépalos y pétalos es: {iris.target_names[(maximo)]}')



Longitud media setal: [5.01 5.94 6.59]
Longitud media petal: [1.46, 4.26, 5.55]
Diferencia de longitudes segun especies: [3.55 1.68 1.04]

La especie con la mayor diferencia entre la longitud media de sépalos y pétalos es: setosa
